services:
  fan-control:
    image: lenovo-ipmi-gpu-control:latest
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environement:
    - HOST=192.168.68.125
    - USER=USERID
    - PASSWORD=PASSW0RD
