services:
  fan-control:
    image: lenovo-ipmi-gpu-control:latest
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      HOST: 192.168.68.123
      USER: USERID
      PASSWORD: PASSW0RD
