version: '3.8'

services:
  fan-control:
    image: fan-control:latest
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
